### PR TITLE
feat(build): generate typescript typings

### PR DESCRIPTION
**Pull request by zewa666**
This is a first shot at trying to automatically generate a typescript typings file. Since the source of your API are swagger files I've made use of [swagger-typescript-codegen](https://github.com/mtennoe/swagger-typescript-codegen), which allows to customize its mustache templates.

Now I needed to hack around a way to camel case the resulting method names, which you can see in `generate-typings.js` with the triple tilde regex replace. But aside from that it looks okayish.

The current state only generates typings for sauce.json. Before I continue with the rest I'd like to get your feedback whether this is something of interest.

To generate typings just run `npm run generate:typings` and you can find the file `index.d.ts` inside the `build` folder.

# Todo
* [x] add to prepublishOnly npm script
* [x] Generate typings for multiple apis
  > everything thats contained inside `/apis/*` is treated as individual schema file
* [x] Full typings for complete options interface (user, key, region, headless)
* [x] Properly generate individual vs complex paramters
* [x] treat in:body parameters properly (schema defines type)
* [x] Fixup generated method return values
* [x] duplicate body params should be switched with a union param

related issue https://github.com/saucelabs/node-saucelabs/issues/42

### CODE REVIEW

**Comment by zewa666** [comment]
Sure we can. This was just regarded as a first WIP so you guys can take a look whether it's something you see fit. I hope to find a bit of time the next few days to add the other APIs and configure the publish chore plus some testing. Thx for the feedback

**Comment by zewa666** [comment]
I'm a step closer, whats now missing is that the return types are a wrapped construct. The original library makes use of superagent, so I'd somehow have to fiddle that out. Lets see how that comes along.

**Comment by zewa666** [comment]
Ouch there is another issue where I'd definitely need your help @christian-bromann. I can't figure out a way to create proper typings for the parameters of functions.

E.g take the following two:

```
api.updateJob(username, id, body)
api.listJobs(username, { ...options })
```

In above case they are all separately provided parameters whereas later takes `username` as the first and everything else as complex object.

Here's the swagger schema for updateJob

```
"parameters": [
          {
            "$ref": "#/parameters/username"
          },
          {
            "$ref": "#/parameters/id"
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Job"
            }
          }
        ],
```

Here's whats in the swagger schema when it comes to listJobs

```
"operationId": "list_jobs",
        "parameters": [
          {
            "$ref": "#/parameters/username"
          },
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/subaccounts"
          },
          {
            "$ref": "#/parameters/full"
          },
          {
            "default": false,
            "description": "Only return manual jobs",
            "in": "query",
            "name": "manual_only",
            "type": "boolean"
          },
          {
            "default": false,
            "description": "FIXME ---- ?",
            "in": "query",
            "name": "auto_only",
            "type": "boolean"
          },
          {
            "description": "name of the job",
            "in": "query",
            "name": "name",
            "type": "string",
            "required": false
          },
          {
            "description": "owner type for jobs",
            "in": "query",
            "name": "owner_type",
            "type": "string",
            "required": false
          },
          {
            "description": "username of owner of the jobs",
            "in": "query",
            "name": "owner",
            "type": "string",
            "required": false
          },
          {
            "description": "receive jobs beginning of a specific timestamp",
            "in": "query",
            "name": "from",
            "type": "number",
            "required": false
          },
          {
            "description": "receive jobs until specific timestamp",
            "in": "query",
            "name": "to",
            "type": "number",
            "required": false
          }
        ],
```

From the schemas I can't find any indicator on how to treat parameters.
how did you guys decide when to use complex objects vs individual parameters? Is it just for a specific set of parameter-names that you treat them as individuals and everything else as complex?

**Comment by zewa666** [comment]
ahhh could the `"in"` be the indicator? So everything thats `query` is complex whereas `path` and `body` are treated as individual params?

**Comment by christian-bromann** [comment]
everything that's a query or body is a complex object while (optional parameters) while things within the path are individual parameters

**Comment by zewa666** [comment]
are you sure about the `body`?

Looking at [this one](https://github.com/saucelabs/node-saucelabs/blob/master/docs/interface.md#example-27) its implemented as individual param, although defined as in:body

```
{
  "in": "body",
  "name": "body",
  "required": true,
  "schema": {
    "$ref": "#/definitions/Job"
  }
}
```

**Comment by christian-bromann** [comment]
> moreover body cant be optional according to the schema

That is true. So every parameter that is part of the path are direct parameters, the rest of it is provided as an object (last parameter). This object can have required and non required parameters too.

**Comment by zewa666** [comment]
ok yeah I see. So that last param also according [to this](https://github.com/saucelabs/node-saucelabs/blob/master/docs/interface.md#example-9) could be an array of strings.
Phew gonna be interesting to see whether we can squeeze that info out as well in the templates.

@christian-bromann thanks for the clarifications.

**Comment by christian-bromann** [comment]
> could be an array of strings

no, in this case only on ID is allowed

**Comment by zewa666** [comment]
I think we got it so far, with the help of my colleague @gins3000 and some regex black magic.

A thing left is the method `readBatchReport` which results in

```typescript
readBatchReport(
        body ? : number,
        body ? : string,
            ): Promise<BatchReport >
```

which has the following params definition in `rdc.json`

```
"parameters":[
               {
                  "in":"body",
                  "name":"body",
                  "required":false,
                  "schema":{
                     "type":"integer",
                     "format":"int64"
                  }
               },
               {
                  "in":"body",
                  "name":"body",
                  "required":false,
                  "schema":{
                     "type":"string"
                  }
               }
            ],
```

So as seen the body is defined twice. I'm unsure how to proceed here. Manually fix that one up or could that potentially happen more often in future @christian-bromann ?

**Comment by christian-bromann** [comment]
> I'm unsure how to proceed here. Manually fix that one up or could that potentially happen more often in future @christian-bromann ?

The given swagger definition can unfortunately contain outdated data so feel free to just remove one of the parameters.

**Comment by zewa666** [comment]
OOOooooookay, I think I got everything now. I've checked it for a handful methods we're making use of in our [Ranorex Webtestit IDE](https://webtestit.com) and it seems that the typings are correct.

@christian-bromann I'd like to ask you to give this another closer look and see whether you might spot some additional glitches.

**Comment by zewa666** [comment]
Oh yeah a beautifier could have worked wonders here. I'll take a further look at it

**Pull request merged**
