### PR TITLE
Correct types of CLI parameters

### PR DESCRIPTION
**Pull request by martinfrancois**
Types were taken from: https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy+Command-Line+Quick+Reference+Guide

By the way @christian-bromann, I found a mistake in the documentation linked above, it mentions `--readyfile` but I think it should be: `--readyfile <filename>`, can you please have that one corrected? Since it's a Confluence page I cannot edit it myself unfortunately :-)

And can you please tag this PR with `hacktoberfest-accepted` and potentially add the `hacktoberfest` topic to this repository? Thanks!

### CODE REVIEW

**Comment by martinfrancois** [comment]
Any idea why the build fails on Node 8? It looks to be unrelated to my change, but it passes on master... Maybe we need to re-run the build?

**Comment by martinfrancois** [comment]
@christian-bromann did you retry? I can't see it in the builds for some reason... Maybe it would also be good to retry master (as long as that doesn't trigger any deployments or anything) to compare

**Comment by christian-bromann** [comment]
It seems that one of our dev dependencies doesn't support Node 10 anymore.

**Comment by martinfrancois** [comment]
@christian-bromann I think you meant Node 8, right? I fixed it now here: https://github.com/saucelabs/node-saucelabs/pull/98

As soon as that one is merged, I'll rebase this one.

**Comment by martinfrancois** [comment]
@christian-bromann just rebased it and the build now passes!

**Review by christian-bromann — APPROVED** [review]
Awesome, great job!

**Comment by martinfrancois** [comment]
Thanks a lot!

**Comment by martinfrancois** [comment]
@christian-bromann will a release on this one follow soon? Then we could already include it in `@wdio/sauce-service` as well!

**Comment by christian-bromann** [comment]
@martinfrancois just released as v4.5.1

**Pull request merged**
